---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ledger-api-secret
  namespace: payments
spec:
  encryptedData:
    DB_PASSWORD: AgAsNmBvvVzt+8Sa8dnhMAadA0la2bbJFZgv4XmxsAqbX5/XqEF8O/nrsto0b4vLAuqLpFfM5UgAXvL0ahzfb0hhPdQS/KprPYc3Ru8RfUylprd15BP1J3kIeFRY4t7pbTRFHV4aAHQaCMWPSjYppTTXjMc1gR3S0K48XJZZZbeZYGZKKbQG25HTVlRT7VInIwnCUUsVKaOU+Ht4yGUCYIytuqSPe2itgW1GVo4+qTXDh6kNSk2Z8Ewt6PgcUm5kq0nl4JUhAFQ68pUnXQLVnnpVjHg7no4ob3SvVGDM65m29J1ATLaTrVEACE+AGiiMSGhsBC1bmWNXxsl8JoBu+mxU+6n0BF9wZBexh44of/5uqvBNElv8nBfqFaPRj1BMjMf+SCg0k9UNpcgb/pIci2NCo8IL0/2SML5XTsr1CtxI9XGyT6YnssvDBvvMqGXLv84c2qEjb9htUFr6NR/TjGnJZQjD9yjd4Elf8v+u0BjtllQC4JHbz40/ZnOQlE/LfVL9E/Dj54a2pjHCjM3x3TNh2u4cTxXxTxWRBm6fj5ATsPw2QjX+FEJf6G1tpJtwtBCEnQW8bdqarp1/6Eq8kDzMKm4FJkVROu1hwM0zYkF57/AtFnBsR2jnUVWOw335dpUt6Vl/yX0QbGoIbmwrhg4AHxjJGBGfxuGAzwssYl1EeHGT9/vBetmDani8nczlvJY+N26UAR72xGbfSNxrR8s=
    STRIPE_API_KEY: AgArD7GcUHKySjgCXBst/CKPoLMQbKU9evk5vRa1VeeKcc8fSqf2U0szfOV0eUOLM6CQ2qcISf+B8t7uISDrToJ9bhxPiGB78z+nZu+PwsTZF4x7VEu93FfZAs/nKz/QZ6WU41TODrFR0R7a7ZPM38B8aCHtIIgc1HJVSsOgygxtqrNMDas+F1pJWmqxEbF8lE4Vd7dEcBcTBNicQJtRWQnYGjFad4VPngO+xEynHu3dVWD4jeAcoNfNQK3ajrttduGkFYDfrFmTPL4ebC74yejrPbfj+oHy8+x1b0Q9fghoPY93L+rHwjTS6tgyXZImgwb/QLKRwrE0io4T/9JB4zN7NX1dUg+DLMQ1Dub/a/lK7HGDGf+2j1H2G5xwhwLF1dbxcQAJQcB1iDvMe//2MOjX7bY7T9TRH/xMd6+Hj4K0QJgghpOZAlfhHfRbD1qjyFONaRjUewyxVm2xAIrq5ZwfaAOPoWkTFQW442AWGfQI2B94jAEc+DHwC7jcGCbGt5xzhx1OmNb2hkJEskTOLJDiBF+Mk9bKX8GUMiE87grgmqkPPg6sb/vk0H5G8qGymr8h57UeTb2NtZQCidENFaSm2w1GW6SVyf1X6IOKiXuanndUiZS20keZpiDV7CkjDImqsVzprNyL/QqRVELtHjZOXbD9slHphBtNhIG2WQBErNH88SHU6H6utqpwXHyEP0bOZlyEVgbfd3vR5RH8naEHIQ==
  template:
    metadata:
      creationTimestamp: null
      name: ledger-api-secret
      namespace: payments
